version: '3.0'

services:
  app:
    container_name: gramophone_app
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - "5000:5000"
    volumes:
      - ./local/output:/app/static/output
      - ./local/input:/app/static/input
      - ./local/records:/app/static/records
    restart: unless-stopped

  postgres:
    image: postgres:13.11-bullseye
    container_name: gramophone_db
    environment:
      POSTGRES_DB: 'gramophone_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped